spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/questionnaire?serverTimezone=CTT&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/wenjuan?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
#    password: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10

mybatis:
  mapper-locations: classpath:mapperImpl/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true     # 开启驼峰原则，将数据库带下划线的字段自动转为驼峰原则的命名
server:
  port: 8999